version: "3.9"

services:
  synpress:
    container_name: synpress
    platform: linux/amd64
    build: .
    environment:
      - DISPLAY=display:0.0
      - DEBUG=true
    depends_on:
      - display
    entrypoint: []
    working_dir: /app
    command: >
      bash -c 'echo -n "======> local noVNC URL:
      http://localhost:8080/vnc.html?autoconnect=true " && npx wait-on
      http://display:8080 && cd ./scripts && ./run_e2e_tests_ci.sh'
    networks:
      - x11
    volumes:
      - ./docker/videos:/app/e2e/cypress/videos
      - ./docker/screenshots:/app/e2e/cypress/screenshots

  display:
    container_name: display
    image: synthetixio/display:b2643097e891906524e52e7ee956260b20fa01fb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
    ports:
      - "8080:8080"
    networks:
      - x11

  video:
    profiles:
      - synpress
    container_name: video
    image: synthetixio/video:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
      - SE_SCREEN_WIDTH=${SE_SCREEN_WIDTH}
      - SE_SCREEN_HEIGHT=${SE_SCREEN_HEIGHT}
    depends_on:
      - display
    networks:
      - x11

networks:
  x11:
