trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_BUILDKIT: 1
  BACKEND_DIR: $(Build.SourcesDirectory)/backend
  FRONTEND_DIR: $(Build.SourcesDirectory)/frontend
  E2E_DIR: $(Build.SourcesDirectory)/e2e

# Install node (quickly)
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.14.2"
    displayName: "Install: Node.js"

  # Cache/restore hardhat node modules if yarn.lock changed
  - task: Cache@2
    displayName: "Cache: Hardhat node modules"
    inputs:
      key: 'yarn | "$(Agent.OS)" | hardhat | $(Build.SourcesDirectory)/backend/yarn.lock'
      path: $(BACKEND_DIR)/node_modules
      cacheHitVar: HARDHAT_CACHE_RESTORED

  # Yarn install hardhat
  - script: |
      yarn install --frozen-lockfile
    displayName: "Hardhat: yarn install"
    workingDirectory: $(BACKEND_DIR)
    condition: ne(variables.HARDHAT_CACHE_RESTORED, 'true')

  # Cache/restore frontend node modules if yarn.lock changed
  - task: Cache@2
    displayName: "Cache: Frontend node modules"
    inputs:
      key: 'yarn | "$(Agent.OS)" | frontend | $(Build.SourcesDirectory)/frontend/yarn.lock'
      path: $(FRONTEND_DIR)/node_modules
      cacheHitVar: FRONTEND_CACHE_RESTORED

  # Hardhat compile
  - script: |
      npx hardhat compile
    displayName: "Hardhat: Compile smart contracts"
    workingDirectory: $(BACKEND_DIR)

  # Hardhat test
  - script: |
      npx hardhat test
    displayName: "Hardhat: Test smart contracts"
    workingDirectory: $(BACKEND_DIR)

  # Yarn install frontend
  - script: |
      yarn install --frozen-lockfile
    displayName: "Frontend: yarn install"
    workingDirectory: $(FRONTEND_DIR)
    condition: ne(variables.FRONTEND_CACHE_RESTORED, 'true')

  # Build image using Dockerfile & run e2e tests
  - task: DockerCompose@0
    displayName: "E2E: Execute e2e tests"
    inputs:
      action: "Run services"
      containerregistrytype: "Azure Container Registry"
      dockerComposeFile: "docker-compose.yml"
      dockerComposeCommand: "--exit-code-from synpress"
      buildImages: true
      abortOnContainerExit: true
      detached: false
    env:
      DISPLAY_HEIGHT: 1080
      DISPLAY_WIDTH: 1920
      SE_SCREEN_WIDTH: 1366
      SE_SCREEN_HEIGHT: 768

  - publish: $(E2E_DIR)/docker/screenshots
    artifact: screenshots

  - publish: $(E2E_DIR)/docker/videos
    artifact: videos
